sudo: required
services:
    - docker

before_install:
    - docker build -t thegaborantor/chargerhooker .

script:
    - docker run thegaborantor/chargerhooker npm run test -- --coverage

notifications:
    webhooks: https://939vfp3nqj.execute-api.eu-central-1.amazonaws.com/default/RedLightCall
