sudo: required
services:
    - docker

before_install:
    - docker build -t thegaborantor/chargerhooker .

script:
    - docker run thegaborantor/chargerhooker npm run test -- --coverage

notifications:
    webhooks:
        urls:
            - https://ofouzvbk01.execute-api.eu-central-1.amazonaws.com/default/handlePipelineState
        on_success: always
        on_failure: always
        on_error: always
        on_start: never
        on_cancel: never
