sudo: required
services:
    - docker

before_install:
    - docker build -t thegaborantor/chargerhooker .

script:
    - docker run thegaborantor/chargerhooker npm run test -- --coverage

notifications:
    webhooks:
        urls:
            - https://rp5ogapldd.execute-api.eu-central-1.amazonaws.com/default/handleYellowLight
        on_success: never # default:
        on_failure: never # default:
        on_start: always # default: never
        on_cancel: never # default
