sudo: required
services:
    - docker

before_install:
    - docker build -t thegaborantor/chargerhooker .

script:
    - docker run thegaborantor/chargerhooker npm run test -- --coverage

notifications:
    webhooks:
        urls:
            - "https://maker.ifttt.com/trigger/travisci/with/key/$IFTTT_KEY"

        on_failure: always # default: always
        on_error: always
