sudo: required
services:
    - docker

before_install:
    - docker build -t thegaborantor/chargerhooker .

script:
    - docker run thegaborantor/chargerhooker npm run test -- --coverage

notifications:
    webhooks:
        urls:
            - https://939vfp3nqj.execute-api.eu-central-1.amazonaws.com/default/RedLightCall
        on_success: never # default: always
        on_failure: always # default: always
        on_start: never # default: never
        on_cancel: always # default: always
